name = "UnitRangesSortedSets"
uuid = "235ad7fc-2aba-4ca4-9c7c-757ade02a5c7"
authors = ["Denis Telnov <denis.telnov@gmail.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
