name = "UnitRangesSortedSets"
uuid = "72c04766-89e7-4306-a268-94416c2640a0"
authors = ["Denis Telnov <denis.telnov@gmail.com> and contributors"]
version = "0.1.3"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
Aqua = "0.7, 0.8"
BenchmarkTools = "1"
DataStructures = "0.18, 0.19"
julia = "1.6, 1"
Test = "1.6, 1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "BenchmarkTools"]
